=== SZmiycharov/xml-project-2018/08_schema.xsd
<?xml version="1.0"?>

<xs:schema	xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.w3schools.com"
			xmlns="http://www.w3schools.com"
			elementFormDefault="qualified">

	<!-- Simple types -->

	<xs:element name="name" type="xs:string" />

	<xs:element name="webpage" type="xs:string" />

	<xs:element name="students_count" type="xs:positiveInteger" />	

	<xs:element name="description" type="xs:string" />

	<xs:element name="faculty" type="xs:string" />

	<!-- Attributes -->

	<xs:simpleType name="winehouse_id">
		<xs:restriction base="xs:string">
			<xs:pattern value="uni[1-9]([0-9])*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="winehouse_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Частен" />
			<xs:enumeration value="Държавен" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="region_id">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>

	<!-- Complex types -->

	<xs:element name="faculties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="faculty" maxOccurs="unbounded" />
			</xs:sequence>	
		</xs:complexType>
	</xs:element>

	<xs:element name="winehouse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="webpage" />
				<xs:element ref="wines_count" />
				<xs:element ref="description" />
				<xs:element ref="wines" />
			</xs:sequence>
			
			<xs:attribute name="id" type="winehouse_id" use="required" />
			<xs:attribute name="type" type="winehouse_type" use="required" />		
		</xs:complexType>
	</xs:element>

	<xs:element name="region">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">					
					<xs:attribute name="id" type="region_id" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="universities_regions">
		<xs:complexType>
			<xs:attribute name="winehouse_id" type="winehouse_id" use="required" />
			<xs:attribute name="region_id" type="region_id" use="required" />
		</xs:complexType>
	</xs:element>


	<!-- Tags -->

	<xs:element name="universities">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="winehouse" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="regions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="region" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="universities_regions_pairs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="universities_regions" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Document -->

	<xs:element name="universities_catalogue">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="universities" />
				<xs:element ref="regions" />
				<xs:element ref="universities_regions_pairs" />
			</xs:sequence>
		</xs:complexType>
		
		<!-- Keys -->
		
		<xs:key name="regionsKey">
			<xs:selector xpath="universities_catalogue" />
			<xs:field xpath="universities/winehouse/@id" />
			<xs:field xpath="regions/region/@id" />
		</xs:key>
		<xs:keyref name="regionsRef" refer="regionsKey">
			<xs:selector xpath="universities_catalogue/universities_regions_pairs/universities_regions" />
			<xs:field xpath="@winehouse_id" />
			<xs:field xpath="@region_id" />
		</xs:keyref>
		
	</xs:element>

</xs:schema>

=== SZmiycharov/xml-project-2018/08_content.xml
<?xml version="1.0" encoding="utf-8"?>

<?xml-stylesheet type="text/xsl" href="08_transformation.xsl"?>

<universities_catalogue	xmlns="http://www.w3schools.com"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="http://www.w3schools.com 08_schema.xsd">

	<universities>
		<university id="uni1" type="Държавен">
			<name>Софийски университет "Св. Климент Охридски"</name>
			<webpage>https://www.uni-sofia.bg/</webpage>
			<students_count>23769</students_count>
			<description>
				Софийският университет „Св. Климент Охридски“ (СУ) е най-старото и най-голямото висше учебно заведение в България. Освен това той е вторият най-голям изследователски център в България, след БАН.
			</description>
			<faculties>
				<faculty>Исторически факултет</faculty>
				<faculty>Философски факултет</faculty>
				<faculty>Факултет по класически и нови филологии</faculty>
				<faculty>Факултет по славянски филологии</faculty>
				<faculty>Юридически факултет</faculty>
				<faculty>Факултет по педагогика</faculty>
				<faculty>Факултет по начална и предучилищна педагогика</faculty>
				<faculty>Факултет по журналистика и масова комуникация</faculty>
				<faculty>Богословски факултет</faculty>
				<faculty>Стопански факултет</faculty>
				<faculty>Факултет по математика и информатика</faculty>
				<faculty>Физически факултет</faculty>
				<faculty>Факултет по химия и фармация</faculty>
				<faculty>Биологически факултет</faculty>
				<faculty>Геолого-географски факултет</faculty>
				<faculty>Медицински факултет</faculty>
			</faculties>
		</university>
		
		<university id="uni2" type="Държавен">
			<name>Университет за национално и световно стопанство</name>
			<webpage>http://www.unwe.bg/</webpage>
			<students_count>18400</students_count>
			<description>
				Университетът за национално и световно стопанство е най-големият и най-старият икономически университет в Република България. Правоприемник е на Свободния университет за политически и стопански науки, създаден през 1920 г.
			</description>
			<faculties>
				<faculty>Общоикономически факултет</faculty>
				<faculty>Бизнес факултет</faculty>
				<faculty>Факултет „Управление и администрация“</faculty>
				<faculty>Факултет „Приложна информатика и статистика“</faculty>
				<faculty>Финансово-счетоводен факултет</faculty>
				<faculty>Факултет „Икономика на инфраструктурата“</faculty>
				<faculty>Факултет „Международна икономика и политика“</faculty>
				<faculty>Юридически факултет</faculty>
			</faculties>
		</university>
		
		<university id="uni3" type="Частен">
			<name>Нов български университет</name>
			<webpage>http://www.nbu.bg/entrance.php</webpage>
			<students_count>12379</students_count>
			<description>
				Нов български университет (известен още като НБУ) е български частен университет. Основната му база е разположена в София в две сгради (наричани 1-ви и 2-ри корпус), като притежава и други академични бази из страната, а също и собствена университетска библиотека в София — Библиотека на НБУ.
			</description>
			<faculties>
				<faculty>Факултет базово образование</faculty>
				<faculty>Бакалавърски факултет</faculty>
				<faculty>Магистърски факултет</faculty>
				<faculty>Факултет за дистанционно, електронно и продължаващо обучение</faculty>
			</faculties>
		</university>
		
		<university id="uni4" type="Държавен">
			<name>Пловдивски университет "Паисий Хилендарски"</name>
			<webpage>https://www.uni-plovdiv.bg/</webpage>
			<students_count>17825</students_count>
			<description>
				Пловдивският университет „Паисий Хилендарски” (или ПУ) е висше училище в Пловдив, България. Той е водеща културна, образователна и научна институция. ПУ е вторият по големина класически университет в страната след СУ „Св. Климент Охридски“.
			</description>
			<faculties>
				<faculty>Биологически факултет</faculty>
				<faculty>Факултет „Икономически и социални науки“</faculty>
				<faculty>Факултет по математика и информатика</faculty>
				<faculty>Педагогически факултет</faculty>
				<faculty>Физически факултет</faculty>
				<faculty>Филологически факултет</faculty>
				<faculty>Философско-исторически факултет</faculty>
				<faculty>Химически факултет</faculty>
				<faculty>Юридически факултет</faculty>
			</faculties>
		</university>
		
		<university id="uni5" type="Частен">
			<name>Колеж по икономика и администрация</name>
			<webpage>http://www.ceabul.net/web/</webpage>
			<students_count>1507</students_count>
			<description>Колежът по икономика и администрация (съкратено КИА) е висше училище в Пловдив, създадено по решение на Народното събрание, обнародвано в „Държавен вестник“, бр. 97 от 4 септември 2003 г.</description>
			<faculties>
				<faculty>Администраця и управление</faculty>
				<faculty>Икономика</faculty>
				<faculty>Туризъм</faculty>
			</faculties>
		</university>
		
		<university id="uni6" type="Частен">
			<name>Варненски свободен университет "Черноризец Храбър"</name>
			<webpage>http://www.vfu.bg/</webpage>
			<students_count>11497</students_count>
			<description>
				Варненският свободен университет „Черноризец Храбър“ е най-големият частен университет в България със седалище в гр. Варна. Намира се в близост до курортен комплекс Златни пясъци.
			</description>
			<faculties>
				<faculty>Факултет "Международна икономика и администрация"</faculty>
				<faculty>Юридически факултет</faculty>
				<faculty>Архитектурен факултет</faculty>
				<faculty>Департамент "Чуждоезиково обучение"</faculty>
				<faculty>Филиал Смолян</faculty>
			</faculties>
		</university>
		
		<university id="uni7" type="Държавен">
			<name>Великотърновски университет "Св. св. Кирил и Методий"</name>
			<webpage>http://www.uni-vt.bg/1/</webpage>
			<students_count>11867</students_count>
			<description>
				Великотърновският университет „Св. св. Кирил и Методий“ е създаден през 1963 година като Висш педагогически институт „Братя Кирил и Методий“ във Велико Търново. Според неговия уебсайт той е вторият по големина университет в България след СУ "Св. Климент Охридски" и е наследник на просветните и културни традиции на Търновската книжовна школа от 14 век.
			</description>
			<faculties>
				<faculty>Филологически факултет</faculty>
				<faculty>Исторически факултет</faculty>
				<faculty>Юридически факултет</faculty>
				<faculty>Педагогически факултет</faculty>
				<faculty>Стопански факултет</faculty>
				<faculty>Философски факултет</faculty>
				<faculty>Факултет по математика и информатика</faculty>
				<faculty>Православен богословски факултет</faculty>
				<faculty>Факултет по изобразително изкуство</faculty>
			</faculties>
		</university>
		
		<university id="uni8" type="Държавен">
			<name>Американски университет в България</name>
			<webpage>http://www.aubg.bg/</webpage>
			<students_count>1338</students_count>
			<description>
				Американският университет в България, съкратено АУБ (англ. American University in Bulgaria) е частен университет, разположен в Благоевград, България. АУБ следва традиционния американски модел на образование на свободните изкуства, характеризиращ се със съвместно съжителство на студентите в модерен университетски комплекс и с високи критерии за прием.
			</description>
			<faculties>
				<faculty>Факултет за изкуство, филология и литература</faculty>
				<faculty>Факултет по европейски изследвания, история, политически науки и международни отношения</faculty>
				<faculty>Факултет по икономика</faculty>
				<faculty>Факултет по журналистика и масови комуникации</faculty>
				<faculty>Факултет по икономика и мениджмънт</faculty>
				<faculty>Факултет по математически и естествени науки</faculty>
				<faculty>Бизнес колеж</faculty>
			</faculties>
		</university>
	</universities>

	<regions>
		<region id="CA">Sofia, Bulgaria</region>
		<region id="PB">Plovdiv, Bulgaria</region>
		<region id="B">Varna, Bulgaria</region>
		<region id="BT">Veliko Turnovo, Bulgaria</region>
		<region id="E">Blagoevgrad, Bulgaria</region>
	</regions>

	<universities_regions_pairs>
		<universities_regions university_id="uni1" region_id="CA" />
		<universities_regions university_id="uni2" region_id="CA" />
		<universities_regions university_id="uni3" region_id="CA" />
		<universities_regions university_id="uni4" region_id="PB" />
		<universities_regions university_id="uni5" region_id="PB" />
		<universities_regions university_id="uni6" region_id="B" />
		<universities_regions university_id="uni7" region_id="BT" />
		<universities_regions university_id="uni8" region_id="E" />
	</universities_regions_pairs>

</universities_catalogue>
